### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by prjailani**
Update Readme File. I am a Hacktoberfest Contributor.

### CODE REVIEW

**Comment by SCHW18TZ** [comment]
C'mon dude, put some effort into it!

**Comment by prjailani** [comment]
Please wait few minutes I'll add others things too

**Comment by prjailani** [comment]
@SCHW18TZ Hi sir, Is it ok or more thing need to be done. Thanks.

**Comment by SCHW18TZ** [comment]
Please make a seprate files Contributions.MD and add it there

**Comment by prjailani** [comment]
@SCHW18TZ Created

**Comment by SCHW18TZ** [comment]
Thanks for your contribution!

**Pull request merged**
